name: loanlink-crm

services:
  app:
    build:
      context: ./app 
      dockerfile: Dockerfile
    volumes:
      - ../:/home/php/app
    working_dir: /home/php/app
    ports:
      - '8080:8080'
    depends_on:
      - db

  node:
    image: node:22-alpine
    working_dir: /home/node/app
    user: node
    volumes:
      - ../:/home/node/app
    command: sh -c "npm install && npm run dev"
    ports:
      - '3000:3000'
    depends_on:
      - app

  db:
    image: mariadb:11.4-noble
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: loanlink
      MARIADB_USER: loanlink
      MARIADB_PASSWORD: secret
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mariadb_data:
